#pragma once


// CTPJ10Test 对话框

class CTPJ10Test : public CDialog
{
	DECLARE_DYNAMIC(CTPJ10Test)

public:
	CTPJ10Test(CWnd* pParent = NULL);   // 标准构造函数
	virtual ~CTPJ10Test();

// 对话框数据
	enum { IDD = IDD_TEST };

protected:
	virtual void DoDataExchange(CDataExchange* pDX);    // DDX/DDV 支持

	DECLARE_MESSAGE_MAP()
public:
	void upload();
	void download();
public:
	bool endflag;
    bool beenupload;
	afx_msg void OnBnClickedButton20();
	afx_msg void OnBnClickedButton23();
	afx_msg void OnBnClickedButton26();
	afx_msg void OnBnClickedButton29();
	afx_msg void OnBnClickedButton44();
	afx_msg void OnBnClickedButton21();
	afx_msg void OnBnClickedButton24();
	afx_msg void OnBnClickedButton27();
	afx_msg void OnBnClickedButton30();
	afx_msg void OnBnClickedButton45();
	afx_msg void OnBnClickedButton22();
	afx_msg void OnBnClickedButton25();
	afx_msg void OnBnClickedButton28();
	afx_msg void OnBnClickedButton31();
	afx_msg void OnBnClickedButton46();
	afx_msg void OnCbnSelchangeCombo22();
	afx_msg void OnCbnSelchangeCombo23();
	afx_msg void OnCbnSelchangeCombo24();
	afx_msg void OnCbnSelchangeCombo25();
	afx_msg void OnCbnSelchangeCombo31();
	long m_a_1_xpos;
	long m_a_1_xstep;
	long m_a_1_ypos;
	long m_a_1_ystep;
	long m_a_1_zpos;
	long m_a_1_zstep;
	long m_a_1_kpos;
	long m_a_1_kstep;
	long m_a_1_lpos;
	long m_a_1_lstep;
	long m_a_2_xpos;
	long m_a_2_xstep;
	afx_msg void OnBnClickedButton48();
	afx_msg void OnBnClickedButton47();
	afx_msg void OnBnClickedButton49();
	long m_d_1_samplex1;
	long m_d_1_samplex2;
	long m_d_1_samplex3;
	long m_d_1_samplex4;
	long m_d_1_samplex5;
	long m_d_1_samplex6;
	long m_d_1_samplex7;
	long m_d_1_samplex8;
	long m_d_1_samplex9;
	long m_d_1_samplex10;
	long m_d_1_glassx1;
	long m_d_1_glassx2;
	long m_d_1_glassx3;
	long m_d_1_glassx4;
	long m_d_1_glassx5;
	long m_d_1_glassx6;
	long m_d_1_glassx7;
	long m_d_1_glassx8;
	long m_d_1_glassx9;
	long m_d_1_glassx10;
	long m_d_2_sjpos1;
	long m_d_2_sjpos2;
	long m_d_2_sjpos3;
	long m_d_2_sjpos4;
	long m_d_2_sjpos5;
	long m_d_2_sjpos6;
	long m_d_2_sjpos7;
	long m_d_2_sjpos8;
	long m_d_2_sjpos9;
	long m_d_2_sjpos10;
	long m_d_1_sampley;
	long m_d_1_samplez;
	long m_d_1_glassy;
	long m_d_1_glassz;
	long m_a_2_ypos;
	long m_a_2_ystep;
	afx_msg void OnBnClickedButton114();
	afx_msg void OnBnClickedButton115();
	afx_msg void OnBnClickedButton116();
	long m_d_2_qinxie;
	afx_msg void OnBnClickedButton1();
	afx_msg void OnBnClickedButton77();
	afx_msg void OnBnClickedButton78();
	afx_msg void OnBnClickedButton79();
	afx_msg void OnBnClickedButton80();
	afx_msg void OnBnClickedButton2();
	afx_msg void OnBnClickedButton3();
	afx_msg void OnBnClickedButton50();
	afx_msg void OnBnClickedButton51();
	afx_msg void OnBnClickedButton52();
	afx_msg void OnBnClickedButton53();
	afx_msg void OnBnClickedButton54();
	afx_msg void OnBnClickedButton55();
	afx_msg void OnBnClickedButton56();
	afx_msg void OnBnClickedButton57();
	afx_msg void OnBnClickedButton58();
	afx_msg void OnBnClickedButton59();
	afx_msg void OnBnClickedButton60();
	afx_msg void OnBnClickedButton61();
	afx_msg void OnBnClickedButton62();
	afx_msg void OnBnClickedButton63();
	afx_msg void OnBnClickedButton64();
	afx_msg void OnBnClickedButton65();
	afx_msg void OnBnClickedButton66();
	afx_msg void OnBnClickedButton81();
	afx_msg void OnBnClickedButton82();
	afx_msg void OnBnClickedButton83();
	afx_msg void OnBnClickedButton84();
	afx_msg void OnBnClickedButton101();
	long  m_d_1_kgdown;
	long  m_d_1_kgzhuan;
	long  m_d_1_ggzhuan;
	long m_d_1_tplength;
	long m_d_1_tpwidth;
	long m_d_1_tpgong;
	long m_d_1_tpquan;
	long  m_d_2_pianrs;
	long  m_d_2_piants;
	long  m_d_2_pianfr;
	long  m_d_2_pianh2o;
	long  m_d_2_rswaittime;
	long  m_d_2_tswaittime;
	long  m_d_2_frwaittime;
	long  m_d_1_piansamplewritex;
	long  m_d_1_piansamplewritey;
	long  m_d_1_samplewritez;
	long  m_d_1_zilength;
	long  m_d_1_ziwidth;
	long  m_d_1_zige;
	long  m_d_1_piancheckx;
	long  m_d_1_pianchecky;
	long  m_d_1_piancheckz;
	long  m_d_1_piansmearx;
	long  m_d_1_piansmeary;
	long  m_d_1_piansmearz;
	long  m_d_1_pianglasswritex;
	long  m_d_1_pianglasswritey;
	long  m_d_1_glasswritez;
	afx_msg void OnBnClickedButton102();
	afx_msg void OnBnClickedButton103();
	afx_msg void OnBnClickedButton97();
	afx_msg void OnBnClickedButton98();
	afx_msg void OnBnClickedButton99();
	afx_msg void OnBnClickedButton100();
	afx_msg void OnBnClickedButton104();
	afx_msg void OnBnClickedButton105();
	afx_msg void OnBnClickedButton106();
	afx_msg void OnBnClickedButton107();
	afx_msg void OnBnClickedButton111();
	afx_msg void OnBnClickedButton112();
	afx_msg void OnBnClickedButton113();
	long m_d_2_tsnum;
	long m_d_2_frnum;
	afx_msg void OnBnClickedButton118();
	afx_msg void OnBnClickedButton119();
	afx_msg void OnBnClickedButton85();
	afx_msg void OnBnClickedButton75();
	afx_msg void OnBnClickedButton117();
	afx_msg void OnBnClickedButton67();
	afx_msg void OnBnClickedButton68();
	afx_msg void OnBnClickedButton69();
	afx_msg void OnBnClickedButton70();
	afx_msg void OnBnClickedButton71();
	afx_msg void OnBnClickedButton72();
	afx_msg void OnBnClickedButton73();
	afx_msg void OnBnClickedButton74();
	afx_msg void OnBnClickedButton76();
	afx_msg void OnBnClickedButton86();
	afx_msg void OnBnClickedButton87();
	afx_msg void OnBnClickedButton94();
	afx_msg void OnBnClickedButton95();
	afx_msg void OnBnClickedButton96();
	afx_msg void OnBnClickedButton91();
	afx_msg void OnBnClickedButton89();
	afx_msg void OnBnClickedButton90();
	afx_msg void OnBnClickedButton110();
	afx_msg void OnBnClickedButton108();
	afx_msg void OnBnClickedButton109();
	long m_a_1_num;
	afx_msg void OnBnClickedButton120();
	afx_msg void OnBnClickedButton121();
	afx_msg void OnBnClickedButton130();
	afx_msg void OnBnClickedButton122();
	afx_msg void OnBnClickedButton123();
	afx_msg void OnBnClickedButton124();
	afx_msg void OnBnClickedButton125();
	afx_msg void OnBnClickedButton126();
	afx_msg void OnBnClickedButton136();
	afx_msg void OnBnClickedButton129();
	afx_msg void OnBnClickedButton131();
	afx_msg void OnBnClickedButton132();
	afx_msg void OnBnClickedButton128();
	long  m_d_1_smeark;
	afx_msg void OnBnClickedButton137();
	afx_msg void OnBnClickedButton127();
	long m_a_1_zinum;
	long m_d_1_tibi;
	afx_msg void OnBnClickedButton139();
	afx_msg void OnBnClickedButton138();
	afx_msg void OnBnClickedButton133();
	afx_msg void OnBnClickedButton134();
	afx_msg void OnBnClickedButton135();
	long m_d_2_tsspraytime;
	long m_d_2_frspraytime;
	long m_d_2_rsspraytime;
	long m_a_2_tuoseh2o;
	long m_d_2_qingxih2o;
	afx_msg void OnBnClickedButton141();
	afx_msg void OnBnClickedButton143();
	virtual BOOL OnInitDialog();
	afx_msg void OnClose();
	afx_msg void OnBnClickedButton140();
	long m_d_2_gdjspraytime;
	afx_msg void OnBnClickedButton144();
	afx_msg void OnBnClickedButton92();
	afx_msg void OnBnClickedButton93();
	afx_msg void OnBnClickedButton88();
	afx_msg void OnBnClickedButton142();
	afx_msg void OnBnClickedButton145();
	afx_msg void OnBnClickedButton146();
	afx_msg void OnBnClickedButton147();
	afx_msg void OnBnClickedButton148();
	afx_msg void OnBnClickedButton149();
	afx_msg void OnBnClickedButton150();
	afx_msg void OnBnClickedButton151();
	long m_d_2_glassgdtime;
	long m_d_2_rsWashTimes;
	long m_d_2_tsWashTimes;
	long m_d_2_frWashTimes;
	afx_msg void OnBnClickedButton152();
	afx_msg void OnBnClickedButton153();
	afx_msg void OnBnClickedButton154();
	afx_msg void OnCbnSelchangeCombo32();
	afx_msg void OnCbnSelchangeCombo33();
	long m_1_kggspeed;
	long m_1_huanbiy;
	long m_1_tpspeed;
	afx_msg void OnBnClickedButton155();
	afx_msg void OnBnClickedButton156();
	afx_msg void OnBnClickedButton157();
	long m_d_xiaodutime;
	afx_msg void OnBnClickedButton158();
	afx_msg void OnBnClickedButton159();
	afx_msg void OnBnClickedButton160();
	afx_msg void OnBnClickedButton161();
	afx_msg void OnBnClickedButton162();
	afx_msg void OnBnClickedButton163();
	long m_d_2_rsQxptTime;
	long m_d_2_tsQxptTime;
	long m_d_2_frQxptTime;
	afx_msg void OnBnClickedButton164();
	afx_msg void OnBnClickedButton165();
	afx_msg void OnBnClickedButton166();
	afx_msg void OnBnClickedButton167();
	afx_msg void OnBnClickedButton168();
	afx_msg void OnBnClickedButton169();
	long m_1_d_preHotTime;
	long m_1_d_preHotMaxTime;
	long m_1_d_minTimeBeforeTp;
	afx_msg void OnCbnSelchangeCombo1();
	afx_msg void OnCbnSelchangeCombo2();
	afx_msg void OnCbnSelchangeCombo34();
	afx_msg void OnCbnSelchangeCombo35();
	afx_msg void OnBnClickedButton170();
	long m_d_2_glsmrNum;
	long m_d_2_glsmrWashNum;
	long m_d_2_glsmrsprayTime;
	long m_d_2_glsmrQxptsprayTime;
	long m_d_2_glsmrwaitTime;
	long m_d_2_pianmr;
	afx_msg void OnBnClickedButton171();
	afx_msg void OnBnClickedButton172();
	afx_msg void OnBnClickedButton173();
	afx_msg void OnBnClickedButton174();

	afx_msg void OnBnClickedButton175();

	long m_d_2_zeroCorrected;
	afx_msg void OnBnClickedButton176();
};
